-- AlterTable
ALTER TABLE `balcons` ADD COLUMN `datePrevue` DATETIME(3) NULL,
    ADD COLUMN `envoyeProduction` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT') NULL,
    ADD COLUMN `installation` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT') NULL,
    ADD COLUMN `mesure` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT') NULL,
    ADD COLUMN `plan` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT') NULL,
    ADD COLUMN `planApprobationEnvoyeLe` DATETIME(3) NULL,
    ADD COLUMN `prixVenteInstallation` DECIMAL(10, 2) NULL,
    ADD COLUMN `termine` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT') NULL;

-- CreateTable
CREATE TABLE `achats_phase` (
    `id` VARCHAR(191) NOT NULL,
    `commandeId` VARCHAR(191) NOT NULL,
    `phaseNumero` INTEGER NOT NULL,
    `typeAchat` VARCHAR(191) NOT NULL,
    `statut` ENUM('A_FAIRE', 'FAIT', 'RECEPTIONNE', 'PRET_A_RAMASSER', 'BACK_ORDER') NOT NULL DEFAULT 'A_FAIRE',
    `dateEnvoie` DATETIME(3) NULL,
    `dateReception` DATETIME(3) NULL,
    `quantiteNonRecue` INTEGER NULL,
    `codeProduit` VARCHAR(191) NULL,
    `description` VARCHAR(191) NULL,
    `quantite` INTEGER NULL,
    `prixUnitaire` DECIMAL(10, 2) NULL,
    `couleur` VARCHAR(50) NULL,
    `epaisseur` VARCHAR(10) NULL,
    `typeVerre` VARCHAR(50) NULL,
    `longueur` INTEGER NULL,
    `hauteur` INTEGER NULL,
    `notes` TEXT NULL,
    `details` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `achats_phase_commandeId_idx`(`commandeId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `achats_phase` ADD CONSTRAINT `achats_phase_commandeId_fkey` FOREIGN KEY (`commandeId`) REFERENCES `commandes`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
