-- AlterTable
ALTER TABLE `balcons` MODIFY `envoyeProduction` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL,
    MODIFY `installation` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL,
    MODIFY `mesure` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL,
    MODIFY `plan` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL,
    MODIFY `termine` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL;

-- AlterTable
ALTER TABLE `commandes` MODIFY `mesure` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL,
    MODIFY `plan` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL,
    MODIFY `envoyeProduction` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL,
    MODIFY `productionTerminee` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL,
    MODIFY `termine` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL,
    MODIFY `installation` ENUM('COMPLETE', 'ATTENTE_CLIENT', 'NON_APPLICABLE', 'PARTIEL', 'DOSSIER_MESUREUR', 'MODIFICATION', 'ATTENTE_CAROL_CONFIRM', 'ATTENTE_CAROL_MESURE', 'BACK_ORDER', 'ATTENTE_REPRESENTANT', 'APPROBATION_PLAN') NULL;
